# Permalinks
permalink:           pretty

# Setup
title:               adrianwong
tagline:             'programmer &middot; retired coal miner'
description:         '"Programming is like kicking yourself in the face, sooner or later your nose will bleed."'
url:                 https://adrianwong.github.io/
timezone:            Australia/Melbourne
paginate:            1

# Plugins
plugins:             [jekyll-paginate]

# About/contact
author:
  name:              Adrian Wong
  url:               https://adrianwong.github.io/

# Networks
networks:
  - class:           github fa-2x
    url:             https://github.com/adrianwong
  - class:           codepen fa-2x
    url:             https://codepen.io/adrianwong/
  - class:           linkedin fa-2x
    url:             https://www.linkedin.com/in/adrian-wong-31bab653

# Custom vars
version:             1.0.0
