# Permalinks
permalink:          pretty

# Plugins
gems:               [jekyll-sitemap]

# Setup
title:              adrianwong
tagline:            'programmer &middot; retired coal miner'
description:        '"Programming is like kicking yourself in the face, sooner or later your nose will bleed."'
url:                http://adrianwong.pizza
timezone:           Australia/Melbourne

# About/contact
author:
  name:             Adrian Wong
  url:              http://adrianwong.pizza

# Networks
networks:
  - name:           github
    url:            https://github.com/adrianwong
  - name:           codepen
    url:            https://codepen.io/adrianwong/
  - name:           linkedin
    url:            https://www.linkedin.com/in/adrian-wong-31bab653

# Projects
projects:
  - name:           React Mario
    img:            react-mario.png
    desc:           First foray into React. Code is probably atrocious.
    links:
      - type:       Demo
        url:        http://adrianwong.pizza/react-mario
      - type:       GitHub
        url:        https://github.com/adrianwong/react-mario

# Custom vars
version:            1.0.0
