# Permalinks
permalink:          /:categories/:title/

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Setup
title:              adrianwong
tagline:            'programmer &middot; retired coal miner'
description:        '"Programming is like kicking yourself in the face, sooner or later your nose will bleed."'
url:                http://adrianwong.pizza
timezone:           Australia/Melbourne

# About/contact
author:
  name:             Adrian Wong
  url:              http://adrianwong.pizza
