# Permalinks
permalink:           pretty

# Setup
title:               adrianwong
tagline:             'programmer &middot; retired coal miner'
description:         '"Programming is like kicking yourself in the face, sooner or later your nose will bleed."'
url:                 https://adrianwong.github.io/
timezone:            Australia/Melbourne
paginate:            1

# About/contact
author:
  name:              Adrian Wong
  url:               https://adrianwong.github.io/

# Custom vars
version:             1.0.0
